<?php

/*
|--------------------------------------------------------------------------
| Countries
|--------------------------------------------------------------------------
| Static reference data, so it lives in config rather than a table: ISO
| 3166-1 changes a handful of times a decade, and a migration is the wrong
| tool for a list that no administrator will ever edit.
|
| Config, not the intl extension, because intl is not present on every
| machine this runs on — including the one it was written on. A reference
| list that works everywhere beats a prettier one that works sometimes.
|
| Each row: [English name, dial code, default currency].
| `featured` names the markets that get their own place in the UI. Every
| other country is still fully selectable — being unfeatured costs a member
| nothing.
*/

return [

    'featured' => ['BD', 'IN', 'PK', 'US', 'GB', 'CA', 'AU', 'AE', 'SA', 'MY', 'SG', 'ZA'],

    'list' => [
        'AF' => ['Afghanistan', '+93', 'AFN'],
        'AL' => ['Albania', '+355', 'ALL'],
        'DZ' => ['Algeria', '+213', 'DZD'],
        'AR' => ['Argentina', '+54', 'ARS'],
        'AM' => ['Armenia', '+374', 'AMD'],
        'AU' => ['Australia', '+61', 'AUD'],
        'AT' => ['Austria', '+43', 'EUR'],
        'AZ' => ['Azerbaijan', '+994', 'AZN'],
        'BH' => ['Bahrain', '+973', 'BHD'],
        'BD' => ['Bangladesh', '+880', 'BDT'],
        'BB' => ['Barbados', '+1246', 'BBD'],
        'BY' => ['Belarus', '+375', 'BYN'],
        'BE' => ['Belgium', '+32', 'EUR'],
        'BT' => ['Bhutan', '+975', 'BTN'],
        'BO' => ['Bolivia', '+591', 'BOB'],
        'BA' => ['Bosnia and Herzegovina', '+387', 'BAM'],
        'BW' => ['Botswana', '+267', 'BWP'],
        'BR' => ['Brazil', '+55', 'BRL'],
        'BN' => ['Brunei', '+673', 'BND'],
        'BG' => ['Bulgaria', '+359', 'BGN'],
        'KH' => ['Cambodia', '+855', 'KHR'],
        'CM' => ['Cameroon', '+237', 'XAF'],
        'CA' => ['Canada', '+1', 'CAD'],
        'CL' => ['Chile', '+56', 'CLP'],
        'CN' => ['China', '+86', 'CNY'],
        'CO' => ['Colombia', '+57', 'COP'],
        'CR' => ['Costa Rica', '+506', 'CRC'],
        'HR' => ['Croatia', '+385', 'EUR'],
        'CY' => ['Cyprus', '+357', 'EUR'],
        'CZ' => ['Czechia', '+420', 'CZK'],
        'DK' => ['Denmark', '+45', 'DKK'],
        'DO' => ['Dominican Republic', '+1809', 'DOP'],
        'EC' => ['Ecuador', '+593', 'USD'],
        'EG' => ['Egypt', '+20', 'EGP'],
        'SV' => ['El Salvador', '+503', 'USD'],
        'EE' => ['Estonia', '+372', 'EUR'],
        'ET' => ['Ethiopia', '+251', 'ETB'],
        'FJ' => ['Fiji', '+679', 'FJD'],
        'FI' => ['Finland', '+358', 'EUR'],
        'FR' => ['France', '+33', 'EUR'],
        'GE' => ['Georgia', '+995', 'GEL'],
        'DE' => ['Germany', '+49', 'EUR'],
        'GH' => ['Ghana', '+233', 'GHS'],
        'GR' => ['Greece', '+30', 'EUR'],
        'GT' => ['Guatemala', '+502', 'GTQ'],
        'GY' => ['Guyana', '+592', 'GYD'],
        'HN' => ['Honduras', '+504', 'HNL'],
        'HK' => ['Hong Kong', '+852', 'HKD'],
        'HU' => ['Hungary', '+36', 'HUF'],
        'IS' => ['Iceland', '+354', 'ISK'],
        'IN' => ['India', '+91', 'INR'],
        'ID' => ['Indonesia', '+62', 'IDR'],
        'IR' => ['Iran', '+98', 'IRR'],
        'IQ' => ['Iraq', '+964', 'IQD'],
        'IE' => ['Ireland', '+353', 'EUR'],
        'IL' => ['Israel', '+972', 'ILS'],
        'IT' => ['Italy', '+39', 'EUR'],
        'JM' => ['Jamaica', '+1876', 'JMD'],
        'JP' => ['Japan', '+81', 'JPY'],
        'JO' => ['Jordan', '+962', 'JOD'],
        'KZ' => ['Kazakhstan', '+7', 'KZT'],
        'KE' => ['Kenya', '+254', 'KES'],
        'KW' => ['Kuwait', '+965', 'KWD'],
        'KG' => ['Kyrgyzstan', '+996', 'KGS'],
        'LA' => ['Laos', '+856', 'LAK'],
        'LV' => ['Latvia', '+371', 'EUR'],
        'LB' => ['Lebanon', '+961', 'LBP'],
        'LY' => ['Libya', '+218', 'LYD'],
        'LT' => ['Lithuania', '+370', 'EUR'],
        'LU' => ['Luxembourg', '+352', 'EUR'],
        'MO' => ['Macao', '+853', 'MOP'],
        'MG' => ['Madagascar', '+261', 'MGA'],
        'MW' => ['Malawi', '+265', 'MWK'],
        'MY' => ['Malaysia', '+60', 'MYR'],
        'MV' => ['Maldives', '+960', 'MVR'],
        'MT' => ['Malta', '+356', 'EUR'],
        'MU' => ['Mauritius', '+230', 'MUR'],
        'MX' => ['Mexico', '+52', 'MXN'],
        'MD' => ['Moldova', '+373', 'MDL'],
        'MN' => ['Mongolia', '+976', 'MNT'],
        'ME' => ['Montenegro', '+382', 'EUR'],
        'MA' => ['Morocco', '+212', 'MAD'],
        'MZ' => ['Mozambique', '+258', 'MZN'],
        'MM' => ['Myanmar', '+95', 'MMK'],
        'NA' => ['Namibia', '+264', 'NAD'],
        'NP' => ['Nepal', '+977', 'NPR'],
        'NL' => ['Netherlands', '+31', 'EUR'],
        'NZ' => ['New Zealand', '+64', 'NZD'],
        'NI' => ['Nicaragua', '+505', 'NIO'],
        'NG' => ['Nigeria', '+234', 'NGN'],
        'MK' => ['North Macedonia', '+389', 'MKD'],
        'NO' => ['Norway', '+47', 'NOK'],
        'OM' => ['Oman', '+968', 'OMR'],
        'PK' => ['Pakistan', '+92', 'PKR'],
        'PS' => ['Palestine', '+970', 'ILS'],
        'PA' => ['Panama', '+507', 'PAB'],
        'PG' => ['Papua New Guinea', '+675', 'PGK'],
        'PY' => ['Paraguay', '+595', 'PYG'],
        'PE' => ['Peru', '+51', 'PEN'],
        'PH' => ['Philippines', '+63', 'PHP'],
        'PL' => ['Poland', '+48', 'PLN'],
        'PT' => ['Portugal', '+351', 'EUR'],
        'QA' => ['Qatar', '+974', 'QAR'],
        'RO' => ['Romania', '+40', 'RON'],
        'RU' => ['Russia', '+7', 'RUB'],
        'RW' => ['Rwanda', '+250', 'RWF'],
        'SA' => ['Saudi Arabia', '+966', 'SAR'],
        'SN' => ['Senegal', '+221', 'XOF'],
        'RS' => ['Serbia', '+381', 'RSD'],
        'SC' => ['Seychelles', '+248', 'SCR'],
        'SL' => ['Sierra Leone', '+232', 'SLE'],
        'SG' => ['Singapore', '+65', 'SGD'],
        'SK' => ['Slovakia', '+421', 'EUR'],
        'SI' => ['Slovenia', '+386', 'EUR'],
        'SO' => ['Somalia', '+252', 'SOS'],
        'ZA' => ['South Africa', '+27', 'ZAR'],
        'KR' => ['South Korea', '+82', 'KRW'],
        'SS' => ['South Sudan', '+211', 'SSP'],
        'ES' => ['Spain', '+34', 'EUR'],
        'LK' => ['Sri Lanka', '+94', 'LKR'],
        'SD' => ['Sudan', '+249', 'SDG'],
        'SE' => ['Sweden', '+46', 'SEK'],
        'CH' => ['Switzerland', '+41', 'CHF'],
        'SY' => ['Syria', '+963', 'SYP'],
        'TW' => ['Taiwan', '+886', 'TWD'],
        'TJ' => ['Tajikistan', '+992', 'TJS'],
        'TZ' => ['Tanzania', '+255', 'TZS'],
        'TH' => ['Thailand', '+66', 'THB'],
        'TT' => ['Trinidad and Tobago', '+1868', 'TTD'],
        'TN' => ['Tunisia', '+216', 'TND'],
        'TR' => ['Türkiye', '+90', 'TRY'],
        'TM' => ['Turkmenistan', '+993', 'TMT'],
        'UG' => ['Uganda', '+256', 'UGX'],
        'UA' => ['Ukraine', '+380', 'UAH'],
        'AE' => ['United Arab Emirates', '+971', 'AED'],
        'GB' => ['United Kingdom', '+44', 'GBP'],
        'US' => ['United States', '+1', 'USD'],
        'UY' => ['Uruguay', '+598', 'UYU'],
        'UZ' => ['Uzbekistan', '+998', 'UZS'],
        'VE' => ['Venezuela', '+58', 'VES'],
        'VN' => ['Vietnam', '+84', 'VND'],
        'YE' => ['Yemen', '+967', 'YER'],
        'ZM' => ['Zambia', '+260', 'ZMW'],
        'ZW' => ['Zimbabwe', '+263', 'ZWG'],
    ],
];
